### ISSUE TITLE
client component 사용하는게 최선인지 

### ISSUE THREAD

**Issue by eodnjs467** [f-lab-edu/netflix-clone#7]
TMDB를 사용하여 TV시리즈(드라마, 애니메이션 등 시리즈가 있는 것), 영화 리스트를 받아오는 API가 다릅니다.
한 페이지에서 영화, TV 시리즈 전부를 보여주는 상황
하나의 콘텐츠를 클릭하면 상세페이지로 이동 후 상세정보 API 요청을 해야하는데
이 때, 상세 조회하려는 콘텐츠가 TV 시리즈인지, 영화인지 알 수 없는 상황입니다. 

그래서 불러올 때 route.ts 를 사용해서 return NextResponse 반환하기 이전에
 요청 결과값(response)에 contentsType 프로퍼티를 추가하여 반환하도록 하고있습니다.
`const res = await fetch('...');`
`res.contentsType="movie"`;
그 후 상세페이지 클릭시 주소에 쿼리스트링을 통해 `?contentsType="movie"` 와 같이 주소를 설정했기 때문에 
상세페이지를 보여주는 파일에서 useSearchParams를 통해 contentsType 값을 변수에 저장해야하므로 
클라이언트 컴포넌트로 설정했습니다. 

api/browse/route.ts 파일에서 contentsType을 넣어주고 있음.

**Comment by f-lab-kevin** [comment]
[server component query params](https://stackoverflow.com/questions/74889841/how-to-get-query-params-using-server-component-next-13)

혹시 이 링크 확인해보실 수 있을까요?

**Comment by eodnjs467** [comment]
> [server component query params](https://stackoverflow.com/questions/74889841/how-to-get-query-params-using-server-component-next-13)
> 
> 혹시 이 링크 확인해보실 수 있을까요?

넥스트 문서 파일 컨벤션 page 탭에 있었는데 아직 안읽어봐서 몰랐었네요 ㅠㅠ 
안그래도 가끔 예제에서 params 쓰는데 params 설명 나온게 없어서 궁금했는데 이번에 다 읽어봐야겠네요 감사합니다!
https://nextjs.org/docs/app/api-reference/file-conventions/page#searchparams-optional
