### ISSUE TITLE
클라이언트 컴포넌트 에서 서버 컴포넌트 이동 후 뒤로가기 시 error

### ISSUE THREAD

**Issue by eodnjs467** [f-lab-edu/netflix-clone#8]
클라이언트 컴포넌트  ---이동 -->  서버 컴포넌트를 import 해서 사용중인 클라이언트 컴포넌트인 페이지
방문 후 뒤로가기시 error
`Unhandled Runtime Error
Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.`

위 에러가 발생하는데 async/await 현재 서버 컴포넌트에서만 사용 가능하다고 나옵니다. 
'use client' 를 사용하면 하위 컴퍼넌트도 클라이언트 컴포넌트로 작동하는 것으로 알고 있는데 왜 이동했을 때 에러가 안나고 
뒤로가기나 새로고침시 에러가 나는지 .. 
새로고침시에는 데이터 검증, 초기 렌더링 관련 내용때문에 에러가 난다고 생각하지만 뒤로가기는 왜 나는지 모르겠습니다.

**Comment by eodnjs467** [comment]
접속 url : /browse -> /contents/[id]?contentsType -> /series/[id]?contentsType
` /series/[id]?contentsType` 에서 뒤로가기 누르면 에러 발생

**Comment by f-lab-kevin** [comment]
PR에 등록한 syntax 에러로 인해 테스트 환경을 볼 수 없습니다
등록된 PR에 에러가 안나도록 수정해주시면 확인해볼게요

'git clone -> yarn install -> yarn dev' 테스트 한번 확인 부탁드려요 :)

**Comment by eodnjs467** [comment]
서버 컴포넌트와 클라이언트 컴포넌트의 경계를 명확히 했어야했는데 잘못된 사용으로 오류가 났었으나 
수정하여 해결 완료
